ci: cross-build check: set annotation instead of failing the build

diff --git a/.github/workflows/cross-build.yml b/.github/workflows/cross-build.yml
--- a/.github/workflows/cross-build.yml
+++ b/.github/workflows/cross-build.yml
@@ -49,3 +49,7 @@ jobs:
         working-directory: ./cmd/caddy
         run: |
           GOOS=$GOOS go build -trimpath -o caddy-"$GOOS"-amd64
+          if [ $? -ne 0 ]; then
+            echo "::warning ::$GOOS Build Failed"
+            exit 0
+          fi
